[workspace]
resolver = "3"
members = ["configuration"]

[workspace.package]
edition = "2024"

[workspace.dependencies]
schemars = "1.0.4"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
url = "2.5.7"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = "symbols"

[package]
name = "catalog-mcp-server"
version = "0.2.3"
authors = ["Mia-Platform core team"]
edition.workspace = true
rust-version = "1.88"
description = "A Model Context Protocol server to integrate with Mia-Platform Catalog APIs."
documentation = "https://docs.mia-platform.eu/"
homepage = "https://mia-platform.eu/"
repository = "https://github.com/mia-platform/catalog-mcp-server"
license-file = "./LICENSE"

[dependencies]
anyhow = "1.0.100"
axum = { version = "0.8.6", default-features = false, features = [
    "http1",
    "http2",
    "json",
    "tokio",
] }
clap = { version = "4.5.53", features = ["derive", "env"] }
configuration = { path = "configuration" }
dirs = "6.0.0"
http = "1.4.0"
rmcp = { version = "3.4.0", features = ["transport-streamable-http-server"] }
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio = { version = "1.48.0", features = [
    "macros",
    "rt-multi-thread",
    "signal",
    "sync",
    "time",
] }
tokio-util = "0.7.17"
tower = "0.5.2"
tower-http = { version = "0.6.6", features = ["normalize-path", "request-id"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = [
    "env-filter",
    "fmt",
    "json",
] }

[build-dependencies]
configuration = { path = "./configuration", features = ["json-schema"] }
schemars.workspace = true
serde_json.workspace = true

[dev-dependencies]
http-body-util = "0.1.3"
rstest = "0.26.1"

[package.metadata.release]
pre-release-commit-message = "'catalog-mcp-server' tagged at version '{{version}}'"
pre-release-replacements = []
publish = false
push = false
tag-message = "catalog-mcp-server tagged at version {{version}}"
tag-name = "v{{version}}"
