[tasks.check_all]
env = { RUSTFLAGS = "-D warnings" }
script = '''
    cargo clippy --no-default-features;
'''

[tasks.udeps_all]
workspace = false
install_crate = { crate_name = "cargo-udeps", binary = "cargo-udeps", test_arg = "--help" }
toolchain = "nightly"
script = '''
    echo "\nChecking for unused dependencies..."
    cargo +nightly udeps --all-targets --all-features

    echo "\n✓ All valid feature combinations checked for unused dependencies!"
'''
